services:
  alloy:
    image: grafana/alloy:v1.12.1
    container_name: alloy
    ports:
      - "12345:12345"
    volumes:
      - ./alloy:/etc/alloy
      - ./extra/logs/:/var/log:ro
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    restart: unless-stopped
    networks:
      - alloy
    depends_on:
      - loki

  loki:
    image: grafana/loki:main-08e3c43
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./extra/loki/data:/loki
      - ./extra/loki/config:/etc/loki/
    restart: unless-stopped
    networks:
      - alloy

  grafana:
    image: grafana/grafana:12.4.0-20447603318
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_ANALYTICS_REPORTING_ENABLED=false
    volumes:
      - ./extra/grafana/data:/var/lib/grafana
      - ./extra/grafana/config/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./extra/grafana/config/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./extra/grafana/config/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped
    networks:
      - alloy
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:v3.9.0-rc.0
    container_name: prometheus
    mem_limit: 1G
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=1d'
    ports:
      - 9090:9090
    volumes:
      - ./extra/prometheus/config:/etc/prometheus
      - ./extra/prometheus/data:/prometheus
    restart: unless-stopped
    networks:
      - alloy

networks:
  alloy:
    driver: bridge
